development:
  # gRPC server host
  rpc_host: "127.0.0.1:50051"
  # Redis URL (for broadcasting)
  redis_url: "redis://127.0.0.1:6379"
  # Redis channel name
  redis_channel: "anycable"


production:
  # gRPC server host
  rpc_host: "127.0.0.1:50051"
  # Redis URL (for broadcasting)
  redis_url: "redis://127.0.0.1:6379"
  # Redis channel name
  redis_channel: "anycable"